name: Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd frontend && npm install

      - name: Install Playwright Browsers
        run: |
          cd frontend && npx playwright install --with-deps

      - name: Start Frontend Server
        run: |
          cd frontend && npm run dev &
          sleep 5  # Shorter wait time for faster execution

      - name: Run Playwright Tests
        run: |
          cd frontend && npx playwright test tests/homepage.spec.ts
